on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

name: ğŸ“„ Setup Documentation

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: ğŸ“‹ Install Dependencies
        run: pacman --noconfirm -Syu doxygen git

      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: ğŸ”¨ Build
        run: doxygen docs/Doxyfile

      - name: ğŸš€ Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: html

      - name: ğŸ“ƒ Setup Pages
        uses: actions/configure-pages@v5

      - name: ğŸ“¦ Deploy
        uses: actions/deploy-pages@v4
